brave/brave-site-specific-scripts

- webpack.config.js
We need to allow building Typescript in the `node_modules`, as this is required by the `brave-core-crx-packager` which packages the Greaselion CRX.
> Allow typescript in node_modules

- webpack.config.js
We need to allow building Typescript in the node_modules, as this is required by the brave-core-crx-packager which packages the Greaselion CRX.
Follow on to #14.
> Don't exclude node_modules when running webpack

- scripts/brave_rewards/publisher/youtube/youtube.ts
Resolves https://github.com/brave/brave-browser/issues/11883. Test plan is specified in issue.
> Send favicon when visiting YouTube user pages

- Greaselion.json
- scripts/brave_rewards/publisher/common/types.ts
- scripts/brave_rewards/publisher/common/utils.ts
- scripts/brave_rewards/publisher/twitter/auth.ts
- scripts/brave_rewards/publisher/twitter/twitter.ts
- scripts/brave_rewards/publisher/twitter/types.ts
- scripts/brave_rewards/publisher/twitter/utils.test.ts
- scripts/brave_rewards/publisher/twitter/utils.ts
- webpack.config.js
Associated brave-core PR: https://github.com/brave/brave-core/pull/6671
Adds support for Twitter-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel and an injected inline tip button in the user's Twitter feed.
> Add support for Rewards Twitter publishers

- Greaselion.json
- scripts/brave_rewards/publisher/github/_locales/en_US/messages.json
- scripts/brave_rewards/publisher/github/github.ts
- scripts/brave_rewards/publisher/github/types.ts
- scripts/brave_rewards/publisher/github/utils.test.ts
- scripts/brave_rewards/publisher/github/utils.ts
- scripts/brave_rewards/publisher/twitter/twitter.ts
- webpack.config.js
Associated brave-core PR: https://github.com/brave/brave-core/pull/6789
Adds support for Github-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel and an injected inline tip button in the user's Github pages.
> Add support for Rewards Github publishers

- Greaselion.json
- scripts/brave_rewards/publisher/common/types.ts
- scripts/brave_rewards/publisher/common/utils.ts
- scripts/brave_rewards/publisher/reddit/_locales/en_US/messages.json
- scripts/brave_rewards/publisher/reddit/messaging.ts
- scripts/brave_rewards/publisher/reddit/publisherInfo.ts
- scripts/brave_rewards/publisher/reddit/reddit.ts
- scripts/brave_rewards/publisher/reddit/tipping.ts
- scripts/brave_rewards/publisher/reddit/types.ts
- scripts/brave_rewards/publisher/reddit/utils.test.ts
- scripts/brave_rewards/publisher/reddit/utils.ts
- webpack.config.js
Associated brave-core PR: https://github.com/brave/brave-core/pull/6824
Adds support for Reddit-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel and an injected inline tip button in the user's Github pages.
> Add support for Rewards Reddit publishers

- scripts/brave_rewards/publisher/youtube/utils.ts
- scripts/brave_rewards/publisher/youtube/youtube.ts
Resolves https://github.com/brave/brave-browser/issues/12281
- Clean profile
- Enable Rewards
- Visit https://www.youtube.com/channel/UCCs7AQEDwrHEc86r0NNXE_A
- Open Rewards Panel and confirm that Lauren Rees is shown
- Click Youtube logo at top of page
- Click on a creator's name that points to a custom URL (you can check if it's a custom URL by hovering over the creator name and looking at the gray status bar in the bottom left of the browser window - if the URL starts like this `https://youtube.com/c/...` it's a custom URL)
- Open Rewards panel and confirm that creator's name is shown and not Lauren Rees
> Always fetch custom urls

- Greaselion.json
- scripts/brave_rewards/publisher/vimeo/publisherInfo.ts
- scripts/brave_rewards/publisher/vimeo/types.ts
- scripts/brave_rewards/publisher/vimeo/utils.test.ts
- scripts/brave_rewards/publisher/vimeo/utils.ts
- scripts/brave_rewards/publisher/vimeo/vimeoBase.ts
- webpack.config.js
Associated brave-core PR: https://github.com/brave/brave-core/pull/6955
Adds support for Vimeo-based publisher tips via a Greaselion script. The script reacts to URL navigations and state changes by sending the associated publisher info to the Rewards extension, allowing tips to be supported via the Rewards panel.
> Add support for Rewards Vimeo publishers

- scripts/brave_rewards/publisher/common/messaging.ts
- scripts/brave_rewards/publisher/common/tabHandlers.ts
- scripts/brave_rewards/publisher/common/types.ts
- scripts/brave_rewards/publisher/common/utils.ts
- scripts/brave_rewards/publisher/common/webRequestHandlers.ts
- scripts/brave_rewards/publisher/github/githubBase.ts
- scripts/brave_rewards/publisher/github/githubInlineTipping.ts
- scripts/brave_rewards/publisher/github/publisherInfo.ts
- scripts/brave_rewards/publisher/github/tipping.ts
- scripts/brave_rewards/publisher/reddit/publisherInfo.ts
- scripts/brave_rewards/publisher/reddit/redditBase.ts
- scripts/brave_rewards/publisher/reddit/redditInlineTipping.ts
- scripts/brave_rewards/publisher/reddit/tipping.ts
- scripts/brave_rewards/publisher/twitter/api.ts
- scripts/brave_rewards/publisher/twitter/publisherInfo.ts
- scripts/brave_rewards/publisher/twitter/tipping.ts
- scripts/brave_rewards/publisher/twitter/twitterBase.ts
- scripts/brave_rewards/publisher/twitter/twitterInlineTipping.ts
- scripts/brave_rewards/publisher/vimeo/publisherInfo.ts
- scripts/brave_rewards/publisher/vimeo/vimeoBase.ts
- scripts/brave_rewards/publisher/youtube/mediaDuration.ts
- scripts/brave_rewards/publisher/youtube/publisherInfo.ts
- scripts/brave_rewards/publisher/youtube/youtubeBase.ts
As part of https://github.com/brave/brave-browser/issues/12307, the Rewards Greaselion scripts must now communicate with the Brave extension rather than the Rewards extension.
> Rewards scripts will now communicate with the Brave extension

- Greaselion.json
Resolves https://github.com/brave/brave-browser/issues/12968
When we added auto-contribution support to Greaselion in https://github.com/brave/brave-browser/issues/12107 (targeting Brave 1.19), base Vimeo support was also accidentally changed to target Brave 1.19. That was a mistake and it should target Brave 1.18 and above as originally planned.
> Base vimeo support should target Brave 1.18, not 1.19

- scripts/brave_rewards/publisher/common/lruCache.ts
- scripts/brave_rewards/publisher/twitter/api.ts
- scripts/brave_rewards/publisher/twitter/auth.ts
- scripts/brave_rewards/publisher/twitter/publisherInfo.ts
Resolves https://github.com/brave/brave-browser/issues/13578
Limit the number of calls we make to the Twitter API to avoid rate limiting. In addition, cache fetched publisher info in a small LRU cache to avoid making unnecessary calls in the first place.
- Clean profile
- Launch Twitter
- Visit various Twitter users using multiple tabs, switching tabs, scrolling, etc.
- Ensure that we don't call `https://api.twitter.com/1.1/users/show.json?screen_name={$user}` more than once every 3 seconds
> Greaselion makes excessive calls to Twitter API

- scripts/brave_rewards/publisher/twitter/auth.ts
Follow-up to https://github.com/brave/brave-site-specific-scripts/pull/40
After testing, @jonathansampson saw that he was still receiving a 429 error in one scenario. We theorized that Twitter is sending an incorrect HTTP status for a more general error related to incorrect auth headers. We modified our function to ensure that we have appropriate auth headers when logged in or visiting Twitter as a guest.
> Fix Twitter auth headers

- scripts/brave_rewards/publisher/reddit/tipping.ts
Fixes https://github.com/brave/brave-browser/issues/15287.
Positions the Rewards "Tip" button correctly when next to a "More Info" element.
> Position Tip button correctly next to More Info element

- scripts/brave_rewards/publisher/github/tipping.ts
- scripts/brave_rewards/publisher/github/utils.test.ts
- scripts/brave_rewards/publisher/github/utils.ts
Resolves https://github.com/brave/brave-browser/issues/15432
Fix injection of Tip button for starred items in Github. The injection criteria were too wide, resulting in the Tip button being injected into the user's profile page.
> Fix injection of Tip button for starred items tab in Github

- scripts/brave_rewards/publisher/twitter/tipping.ts
A recent change in the Twitter DOM led to misaligned inline tip buttons when visiting a tweet thread. Twitter threads now place their actions in a container that we need to account for.
See https://github.com/brave/brave-browser/issues/24134 for additional details.
> Fix misaligned tip buttons on Twitter

- scripts/brave_rewards/publisher/twitter/tipping.ts
Fixes misaligned inline tip buttons when visiting a tweet thread. Previously we were looking for the actions buttons group, but now the tweet stats are also places in a group which we were finding first. Now we look for the Reply button label attribute and fall back to group.
See https://github.com/brave/brave-browser/issues/24710 for additional details.
> Fix alignment of tip button on Twitter.

- scripts/brave_rewards/publisher/github/tipping.ts
See https://github.com/brave/brave-browser/issues/18494
and https://github.com/brave/brave-browser/issues/25528
The DOM has changed, the name and the username are now placed into an additional `div` for which we have to account.
Also, the text itself is now the `a` tag so we can simplify looking for the username when the tip button is clicked.
> Fix alignment of tip button on Github people page.

- scripts/brave_rewards/publisher/common/utils.ts
- scripts/brave_rewards/publisher/vimeo/utils.ts
Resolves https://github.com/brave/brave-browser/issues/21062
Decode HTML entities when displaying Vimeo publisher names in the Rewards panel. Approach is based on https://stackoverflow.com/questions/1912501/unescape-html-entities-in-javascript/34064434#34064434 which allows decoding more entities while not introducing XSS vulnerabilities.
> Decode HTML entities when displaying Vimeo publisher name

- scripts/brave_rewards/publisher/github/_locales/en_US/messages.json
- scripts/brave_rewards/publisher/github/tipping.ts
- scripts/brave_rewards/publisher/reddit/_locales/en_US/messages.json
- scripts/brave_rewards/publisher/reddit/tipping.ts
- scripts/brave_rewards/publisher/twitter/_locales/en_US/messages.json
- scripts/brave_rewards/publisher/twitter/tipping.ts
Resolves https://github.com/brave/brave-browser/issues/28699
Remove inline tips hover text.
QA note: In my testing, it seemed like the hover text for Twitter and Reddit was non-functional even before this change, probably due to underlying DOM changes.
> Remove inline tips hover text

- Greaselion.json
Resolves https://github.com/brave/brave-browser/issues/32107
For now, we will just remove the Twitter inline tips script from the `Greaselion.json` file.
> Remove Twitter inline tip buttons

- scripts/brave_rewards/publisher/twitter/detector.ts
- scripts/brave_rewards/publisher/twitter/publisherInfo.ts
Resolves https://github.com/brave/brave-browser/issues/40822
> Fix twitter publisher detection
