README.md
=> Fix direct link path to greaselion.json

.gitignore, package-lock.json, package.json, tsconfig.json, webpack.config.js
No test plan for this as it doesn't have any scripts yet. This is just the basis for all the incoming PRs which have actual site scripts. Not sure which will land first.
=> Typescript and Webpack support

package-lock.json
how this was generated: i deleted package-lock and did a fresh npm install
test plan: npm audit should exit cleanly
=> fix npm audit minimist error

.gitignore, package-lock.json, package.json, webpack.config.js
Resolves https://github.com/brave/brave-site-specific-scripts/issues/12
=> Fixes npm audit

scripts/brave_rewards/publisher/youtube/youtube.ts
Resolves brave/brave-browser#11888. Test plan is specified in issue.
=> Don't send empty publisher name to server

Greaselion.json, scripts/brave_rewards/publisher/common/locale.ts, scripts/brave_rewards/publisher/twitter/_locales/en_US/messages.json, scripts/brave_rewards/publisher/twitter/twitter.ts, webpack.config.js
Resolves https://github.com/brave/brave-browser/issues/11890
=> Update Twitter script with localizations

.gitignore, Greaselion.json, README.md, scripts/brave_together/confabs/oneOnOneMeetings.ts, webpack.config.js
For Brave Together, we need to trigger some CSS "magic" if Brave Ads are enabled. This PR does that, and fixes a small typo in the README file (thereby demonstrating I actually do read these things...
=> Together ads enabled

.gitignore, Greaselion.json, scripts/brave_rewards/publisher/twitch/twitchBase.ts, scripts/brave_rewards/publisher/twitch/types.ts, scripts/brave_rewards/publisher/twitch/utils.test.ts, scripts/brave_rewards/publisher/twitch/utils.ts, webpack.config.js
Associated brave-core PR: https://github.com/brave/brave-core/pull/7019
Adds rewards publisher scripts for Twitch.
=> Add support for Rewards Twitch publishers

scripts/brave_rewards/publisher/common/locale.ts, scripts/brave_rewards/publisher/common/messaging.ts, scripts/brave_rewards/publisher/common/tabHandlers.ts, scripts/brave_rewards/publisher/common/utils.test.ts, scripts/brave_rewards/publisher/common/utils.ts, scripts/brave_rewards/publisher/common/webRequestHandlers.ts, scripts/brave_rewards/publisher/github/publisherInfo.ts, scripts/brave_rewards/publisher/github/tipping.ts, scripts/brave_rewards/publisher/github/utils.ts, scripts/brave_rewards/publisher/reddit/publisherInfo.ts, scripts/brave_rewards/publisher/reddit/tipping.ts, scripts/brave_rewards/publisher/reddit/utils.test.ts, scripts/brave_rewards/publisher/reddit/utils.ts, scripts/brave_rewards/publisher/twitter/api.ts, scripts/brave_rewards/publisher/twitter/auth.ts, scripts/brave_rewards/publisher/twitter/publisherInfo.ts, scripts/brave_rewards/publisher/twitter/tipping.ts, scripts/brave_rewards/publisher/twitter/utils.test.ts, scripts/brave_rewards/publisher/twitter/utils.ts, scripts/brave_rewards/publisher/vimeo/publisherInfo.ts, scripts/brave_rewards/publisher/vimeo/utils.ts, scripts/brave_rewards/publisher/youtube/publisherInfo.ts, scripts/brave_rewards/publisher/youtube/utils.test.ts, scripts/brave_rewards/publisher/youtube/utils.ts, scripts/brave_rewards/publisher/youtube/youtubeAutoContribution.ts, scripts/brave_rewards/publisher/youtube/youtubeBase.ts, tslint.json
Resolves https://github.com/brave/brave-browser/issues/12874
Adds `max-line-length` rule to linter and updates all scripts to obey the new rule.
=> Add max-line-length rule to linter rules

Jenkinsfile
Requires for https://github.com/brave/devops/issues/4010
=> Add Jenkinsfile for PR check

scripts/brave_rewards/publisher/common/styles.ts, scripts/brave_rewards/publisher/github/tipping.ts, scripts/brave_rewards/publisher/reddit/tipping.ts, scripts/brave_rewards/publisher/twitter/tipping.ts
Resolves https://github.com/brave/brave-browser/issues/13273
=> Use new SVG for inline tipping icon

scripts/brave_rewards/publisher/youtube/publisherInfo.ts
Resolves https://github.com/brave/brave-browser/issues/13616
=> Specify media type when saving publisher info for YouTube

scripts/brave_rewards/publisher/github/tipping.ts
Resolves https://github.com/brave/brave-browser/issues/13470
When clicking a checkbox in a Github issue, the DOM mutates and ends up removing our inserted inline tip button. After 3 seconds, our configure code will kick in and readd the button but that's enough time to make it look like the button disappeared and reappeared. Instead of waiting for configure to kick off via the timer, listen for relevant changes to the DOM and call configure immediately when noticed.
=> Reconfigure inline tip buttons when relevant portion of DOM changes

jest.config.js, package.json, tsconfig-lint.json, webpack.config.js
Apply tslint to *.js files for consistency
=> Webpack + lint config cleanup

scripts/brave_rewards/publisher/github/utils.ts
Remove useless regex character escape found by CodeQL.
=> Fix useless regex character escape

scripts/brave_rewards/publisher/reddit/publisherInfo.ts, scripts/brave_rewards/publisher/reddit/tipping.ts, scripts/brave_rewards/publisher/reddit/utils.test.ts, scripts/brave_rewards/publisher/reddit/utils.ts
Fix https://github.com/brave/brave-browser/issues/15687
Along with the issue described above there seemed to have been several other issues with our Reddit integration due to changes in the Reddit DOM, so I fixed those at the same time. These included:
- Fixed injection of Tip button in Reddit comments
- Fixed positioning of Tip button on a few pages
- Don't show publisher info for subreddits, as it causes confusion and is potentially misleading
- Clean profile
- Enable Rewards
- Login to Reddit
- Visit https://www.reddit.com/user/TheVictorieeMan
- Open panel and verify that publisher info is correct
- Click "Send a tip" and verify that tip banner info is correct
- On the Reddit page, click the "Tip" icon in one of the comments and verify that tip banner info is correct
- Visit …
=> Rewards Reddit DOM fixes

scripts/brave_rewards/publisher/reddit/tipping.ts
Fixes https://github.com/brave/brave-browser/issues/20544
A recent change in the Reddit DOM led to misaligned tip buttons in posts and responses.
=> Fix alignment of tip button on Reddit

scripts/brave_rewards/publisher/twitter/tipping.ts
Fixes https://github.com/brave/brave-browser/issues/26880
Fixes https://github.com/brave/brave-browser/issues/27256
=> Fix alignment of tip button on Twitter.

scripts/brave_rewards/publisher/reddit/publisherInfo.ts, scripts/brave_rewards/publisher/reddit/tipping.ts, scripts/brave_rewards/publisher/reddit/utils.ts
Instead of retrieving profile data from the profile page itself, use about.json file.
Fixes brave/brave-browser#12241
=> Improves loading performance of the Reddit tipping banner.

scripts/brave_rewards/publisher/github/tipping.ts
Fixes https://github.com/brave/brave-browser/issues/26174
=> Remove tipping button from GitHub people pages.

Greaselion.json, scripts/brave_rewards/publisher/twitter/api.ts, scripts/brave_rewards/publisher/twitter/types.ts
Resolves https://github.com/brave/brave-browser/issues/38461
=> Load twitter scripts on x.com

Greaselion.json
Resolves https://github.com/brave/brave-browser/issues/40784
=> Add missing rewards_enabled preconditions
